### ISSUE TITLE
Upgrade Nextjs 

### ISSUE THREAD

**Issue by SahilLangoo** [natterstefan/nextjs-template#38]
# Feature Request

Upgrade Next js to v11
It has webpack 5 and eslint integrated
Tailwind CSS to v2.2.4
latest jit compiler intergrated

## Motivation

will decrease dependencies, new features

**Comment by natterstefan** [comment]
Thanks @SahilLangoo, I'll take care of it.

**Comment by SahilLangoo** [comment]
Great!
